name: Build PSP EBOOT

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest

    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4

      - name: Compilar com PSPSDK
        run: make

      - name: Enviar EBOOT.PBP como artefato
        uses: actions/upload-artifact@v4
        with:
          name: TurboDash-EBOOT
          path: EBOOT.PBP
